/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "Bisrat Kebere",
  "tagline": "Software Engineer",
  "url": "https://bisrat.tech",
  "baseUrl": "/",
  "trailingSlash": true,
  "deploymentBranch": "gh-pages",
  "organizationName": "BisRyy",
  "projectName": "site",
  "customFields": {},
  "themeConfig": {
    "internetProfiles": {
      "github": {
        "label": "GitHub",
        "href": "https://github.com/BisRyy"
      },
      "leetcode": {
        "label": "Leetcode",
        "href": "https://leetcode.com/BisRy"
      },
      "linkedin": {
        "label": "LinkedIn",
        "href": "https://www.linkedin.com/in/BisRy"
      },
      "medium": {
        "label": "Medium",
        "href": "https://medium.com/@BisRy"
      },
      "twitter": {
        "label": "Twitter",
        "href": "https://twitter.com/BisRyyy"
      },
      "facebook": {
        "label": "Facebook",
        "href": "https://www.facebook.com/Bisrat.Gr/"
      },
      "telegram": {
        "label": "Telegram",
        "href": "https://t.me/BisRy"
      },
      "instagram": {
        "label": "Instagram",
        "href": "https://www.instagram.com/bisrat_gr/"
      }
    },
    "navbar": {
      "logo": {
        "alt": "BisRy Logo",
        "src": "https://github.com/Bisryy.png",
        "width": 32,
        "style": {
          "borderRadius": "50%"
        }
      },
      "items": [
        {
          "to": "blog",
          "label": "Blog",
          "position": "left"
        },
        {
          "to": "resume",
          "label": "Resume",
          "position": "left"
        },
        {
          "to": "goals",
          "label": "Life Goals",
          "position": "left"
        },
        {
          "href": "https://github.com/BisRyy",
          "label": "GitHub",
          "position": "right"
        }
      ],
      "hideOnScroll": false
    },
    "footer": {
      "style": "dark",
      "links": [
        {
          "title": null,
          "items": []
        },
        {
          "title": "Professional",
          "items": [
            {
              "label": "GitHub",
              "href": "https://github.com/BisRyy"
            },
            {
              "label": "Leetcode",
              "href": "https://leetcode.com/BisRy"
            },
            {
              "label": "LinkedIn",
              "href": "https://www.linkedin.com/in/BisRy"
            },
            {
              "label": "Medium",
              "href": "https://medium.com/@BisRy"
            }
          ]
        },
        {
          "title": "Social",
          "items": [
            {
              "label": "Telegram",
              "href": "https://t.me/BisRy"
            },
            {
              "label": "Twitter",
              "href": "https://twitter.com/BisRyyy"
            },
            {
              "label": "Facebook",
              "href": "https://www.facebook.com/Bisrat.Gr/"
            },
            {
              "label": "Instagram",
              "href": "https://www.instagram.com/bisrat_gr/"
            }
          ]
        },
        {
          "title": null,
          "items": []
        }
      ]
    },
    "colorMode": {
      "defaultMode": "light",
      "disableSwitch": false,
      "respectPrefersColorScheme": false
    },
    "docs": {
      "versionPersistence": "localStorage",
      "sidebar": {
        "hideable": false,
        "autoCollapseCategories": false
      }
    },
    "metadata": [],
    "prism": {
      "additionalLanguages": [],
      "theme": {
        "plain": {
          "color": "#bfc7d5",
          "backgroundColor": "#292d3e"
        },
        "styles": [
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(105, 112, 152)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "string",
              "inserted"
            ],
            "style": {
              "color": "rgb(195, 232, 141)"
            }
          },
          {
            "types": [
              "number"
            ],
            "style": {
              "color": "rgb(247, 140, 108)"
            }
          },
          {
            "types": [
              "builtin",
              "char",
              "constant",
              "function"
            ],
            "style": {
              "color": "rgb(130, 170, 255)"
            }
          },
          {
            "types": [
              "punctuation",
              "selector"
            ],
            "style": {
              "color": "rgb(199, 146, 234)"
            }
          },
          {
            "types": [
              "variable"
            ],
            "style": {
              "color": "rgb(191, 199, 213)"
            }
          },
          {
            "types": [
              "class-name",
              "attr-name"
            ],
            "style": {
              "color": "rgb(255, 203, 107)"
            }
          },
          {
            "types": [
              "tag",
              "deleted"
            ],
            "style": {
              "color": "rgb(255, 85, 114)"
            }
          },
          {
            "types": [
              "operator"
            ],
            "style": {
              "color": "rgb(137, 221, 255)"
            }
          },
          {
            "types": [
              "boolean"
            ],
            "style": {
              "color": "rgb(255, 88, 116)"
            }
          },
          {
            "types": [
              "keyword"
            ],
            "style": {
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "doctype"
            ],
            "style": {
              "color": "rgb(199, 146, 234)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "color": "rgb(178, 204, 214)"
            }
          },
          {
            "types": [
              "url"
            ],
            "style": {
              "color": "rgb(221, 221, 221)"
            }
          }
        ]
      },
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    }
  },
  "presets": [
    [
      "@docusaurus/preset-classic",
      {
        "docs": false,
        "theme": {
          "customCss": "/home/bisry/Documents/Project/site/src/css/custom.css"
        }
      }
    ]
  ],
  "plugins": [
    [
      "@docusaurus/plugin-google-gtag",
      {
        "id": "universal-analytics",
        "trackingID": "UA-44622716-1",
        "anonymizeIP": true
      }
    ]
  ],
  "baseUrlIssueBanner": true,
  "i18n": {
    "defaultLocale": "en",
    "path": "i18n",
    "locales": [
      "en"
    ],
    "localeConfigs": {}
  },
  "onBrokenLinks": "throw",
  "onBrokenMarkdownLinks": "warn",
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "themes": [],
  "scripts": [],
  "stylesheets": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false
};
